# Generated by Django 5.2.12 on 2026-03-07 23:10

import django.db.models.deletion
from django.db import migrations, models

import task2_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("change_type", models.CharField()),
                ("object_type", models.CharField(db_index=True)),
                ("object_pid", models.CharField(db_index=True, max_length=16)),
                ("changes", models.JSONField(null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "pid",
                    models.CharField(
                        default=task2_api.models.generate_pid,
                        editable=False,
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField()),
                ("date_of_incorporation", models.DateField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IdentityFile",
            fields=[
                (
                    "pid",
                    models.CharField(
                        default=task2_api.models.generate_pid,
                        editable=False,
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaxInfo",
            fields=[
                (
                    "pid",
                    models.CharField(
                        default=task2_api.models.generate_pid,
                        editable=False,
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tin", models.CharField()),
                ("country", models.CharField(max_length=2)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "pid",
                    models.CharField(
                        default=task2_api.models.generate_pid,
                        editable=False,
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="directors",
                        to="task2_api.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DirectorIdentityFile",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "director_pid",
                        "identityfile_pid",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "director_pid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="task2_api.director",
                    ),
                ),
                (
                    "identityfile_pid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="task2_api.identityfile",
                    ),
                ),
            ],
            options={
                "db_table": "task2_api_director_identity_files",
            },
        ),
        migrations.AddField(
            model_name="director",
            name="identity_files",
            field=models.ManyToManyField(
                related_name="directors",
                through="task2_api.DirectorIdentityFile",
                to="task2_api.identityfile",
            ),
        ),
        migrations.CreateModel(
            name="Shareholder",
            fields=[
                (
                    "pid",
                    models.CharField(
                        default=task2_api.models.generate_pid,
                        editable=False,
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField()),
                ("percentage", models.IntegerField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shareholders",
                        to="task2_api.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShareholderIdentityFile",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "shareholder_pid",
                        "identity_file_pid",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "identity_file_pid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="task2_api.identityfile",
                    ),
                ),
                (
                    "shareholder_pid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="task2_api.shareholder",
                    ),
                ),
            ],
            options={
                "db_table": "task2_api_shareholder_identity_files",
            },
        ),
        migrations.AddField(
            model_name="shareholder",
            name="identity_files",
            field=models.ManyToManyField(
                related_name="shareholders",
                through="task2_api.ShareholderIdentityFile",
                to="task2_api.identityfile",
            ),
        ),
        migrations.CreateModel(
            name="DirectorTaxInfo",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "director_pid",
                        "taxinfo_pid",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "director_pid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="task2_api.director",
                    ),
                ),
                (
                    "taxinfo_pid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="task2_api.taxinfo",
                    ),
                ),
            ],
            options={
                "db_table": "task2_api_director_taxinfo",
            },
        ),
        migrations.AddField(
            model_name="director",
            name="taxinfo",
            field=models.ManyToManyField(
                related_name="directors",
                through="task2_api.DirectorTaxInfo",
                to="task2_api.taxinfo",
            ),
        ),
        migrations.CreateModel(
            name="CompanyTaxInfo",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "company",
                        "taxinfo",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="task2_api.company",
                    ),
                ),
                (
                    "taxinfo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="task2_api.taxinfo",
                    ),
                ),
            ],
            options={
                "db_table": "task2_api_company_taxinfo",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="taxinfo",
            field=models.ManyToManyField(
                related_name="companies",
                through="task2_api.CompanyTaxInfo",
                to="task2_api.taxinfo",
            ),
        ),
    ]
